# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: abbc5fdf97f32d84dd4700d2e6bd0a41ba3314640f547505b367bb97ec205b997a40d61196e2a785db2f7079ddfd0ca6c4413e930cfbfc8f241c4e240855394f

test:
  secret_key_base: 3efd52dfd6f667f10d23595695138118cd1fe65b5b1c13152820f924da9fa9c40118fa0ea640e226b71ec85727f9f865fec14a00a7e568324a37d956eeaf6bf4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
